### ISSUE TITLE
Convert Ecto.Query to Cilckhouse sql

### ISSUE THREAD

**Issue by Zarathustra2** [balance-platform/pillar#66]
Has there been any thoughts about converting an `Ecto.Query` to valid clickhouse sql? 

That way users could write queries using `Ecto.Query` and then convert the ecto queries to valid clickhouse SQL? 

We could start with just some simple queries and support the basics.

Thoughts?

**Comment by sofakingworld** [comment]
When I started this library, there was clickhouse with major 19 version. 

This version had only "SELECT" and "INSERT" statements. That's why I didn't add Ecto.Query protocol

Btw I have no experience with Ecto.Query on low-level, and do you?

May be combine with this library? :) 
https://github.com/clickhouse-elixir/clickhouse_ecto

**Comment by Zarathustra2** [comment]
I have a bit of experience. I will try to get some prototype working! :)

**Comment by daviaws** [comment]
Any progress on this?
I'm interested in use Clickhouse and pillar too... but loosing compatibility with Ecto.Query API is one of the downsides...

If there is any progress on it or if I can help, please, let me know!

**Comment by Zarathustra2** [comment]
@daviaws use https://github.com/plausible/ecto_ch

**Comment by sofakingworld** [comment]
I close the issue, cause Ecto support is not planned
